---
- name: 'Install httpd'
  yum:
    name: httpd
    state: latest

- name: 'Start and Enable httpd'
  systemd:
    name: httpd
    state: started
    enabled: yes
    masked: no

- name: 'Firewalld: Open http'
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes