---
- name: 'Install targetcli'
  yum:
    name: targetcli.noarch
    state: latest

- name: 'Start and Enable target.service'
  systemd:
    name: target.service
    state: started
    enabled: yes
    masked: no

- name: 'Firewalld: Open 3260/tcp'
  firewalld:
    port: 3260/tcp
    permanent: true
    state: enabled
    immediate: yes
