---
- name: 'Install iscsi-initiator-utils.x86_64'
  yum:
    name: iscsi-initiator-utils.x86_64
    state: latest

- name: 'Set initiatorname'
  shell: echo 'InitiatorName=iqn.2017-01.com.pcs:'$(hostname) > /etc/iscsi/initiatorname.iscsi

- name: 'Start and Enable iscsid.service'
  systemd:
    name: iscsid.service
    state: started
    enabled: yes
    masked: no

- name: 'Discover target'
  command: iscsiadm --mode discoverydb --type sendtargets --portal 192.168.30.10 --discover

- name: 'Login to target'
  command: iscsiadm --mode node --targetname iqn.2017-01.com.pcs:iscsi --portal 192.168.30.10:3260 --login
