---
- name: common
  hosts: all
  become: yes
  roles:
    - common

- name: target
  hosts: iscsi
  become: yes
  roles:
    - iscsitarget

- name: initiators
  hosts: pcs1 pcs2
  become: yes
  roles:
    - iscsiinitiator
#    - pcsstuff
